services:
  tondo-api:
    image: ${API_IMAGE:-my-local-api:local}
    build: .
    container_name: tondo-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always