spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    bedrock:
      model-id: ${BEDROCK_MODEL_ID}
      image-model-id: ${BEDROCK_IMAGE_MODEL_ID}
      image-region: us-west-2

app:
  frontend:
    base-url: "https://tondo.app"