spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true # 쿼리 확인을 위해 추가하면 좋습니다
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

app:
  frontend:
    base-url: ${FRONTEND_URL}