spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tondo
    username: tondo
    password: tondo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

app:
  frontend:
    base-url: "http://localhost:3000"